DjangoTest/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DjangoTest.views.home', name='home'),
    # url(r'^DjangoTest/', include('DjangoTest.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^members/', include('members.urls', namespace="members")),
    url(r'^galleries/', include('galleries.urls', namespace="galleries")),
    url(r'^signup/', 'members.views.registration', name='signup'),
    url(r'^login/', 'members.views.loginRequest', name='login'),
    url(r'^logout/', 'members.views.logoutRequest', name='logout'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import patterns,url
from django.views.generic import DetailView, ListView
from django.utils import timezone

from polls import views
from polls.models import Poll

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$',
        ListView.as_view(
            queryset=Poll.objects.filter(pub_date__lte=timezone.now) \
                .order_by('-pub_date')[:5],
            context_object_name='latest_poll_list',
            template_name='polls/index.html'),
        name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            queryset=Poll.objects.filter(pub_date__lte=timezone.now),
            model=Poll,
            template_name='polls/detail.html'),
        name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>\d+)/results/$',
        DetailView.as_view(
            model=Poll,
            template_name='polls/results.html'),
        name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote', name='vote'),
)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" rel="stylesheet">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/js/bootstrap.min.js"></script>
    <title>{% block title %}Test Site{% endblock %}</title>
    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <div class="container">

                <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <!-- Everything you want hidden at 940px or less, place within here -->
                <div class="nav-collapse collapse">
                    <!-- .nav, .navbar-search, .navbar-form, etc -->
                </div>

                <ul class="nav">
                    <li class="active">
                        <a class="brand" href="{% url 'members:index' %}">Test Site</a>
                    </li>
                    <li><a href="{% url 'members:index' %}">Members</a></li>
                    <li><a href="{% url 'signup' %}">Sign-Up</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}

                </ul>

            </div>
        </div>
    </div>
</head>
<body>
<div class="navbar navbar-inverse"></div>
    <h1>Test Site</h1>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>